services:
  pg:
    image: postgres:18.1-alpine3.23
    container_name: pg
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ivan
      POSTGRES_PASSWORD: aXZhbiBwb3Bvdg==
      POSTGRES_DB: kitypes
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.1-alpine3.20
    restart: always
    env_file: 
      - .env
    ports:
      - 7000:6379
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
